### ISSUE TITLE
Unable to Update...

### ISSUE THREAD

**Issue by BallisticPain** [xdan/periodpicker#32]
I'm unable to update to the latest version. I tried logging in with my receipt information it says my period has expired. :( I need this ASAP! We have an issue where we cannot update the time.

**Comment by BallisticPain** [comment]
Found the update form at: http://xdsoft.net/jqplugins/periodpicker/?update#plugin_sender

**Comment by kudlatyamroth** [comment]
I tried use that form, but i allways get error: "Error! Your order is not found . If you just bought a product then please wait for some time"

when it will be available? i bought Professional edition on 15.11.2018, today is 4 days after and i can't update. In email i get version 6.1.8, and i read that bugs that i faced is fixed in 6.2.8 but i can't update...
